# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: Bali // Canggu
description: Discover our exceptional locations to explore, work remotely and meet inspiring people.
keywords: "Live Differently, Work from Anywhere, Location Independant, Digital Nomads"

# author settings for cc-by
author: Robert Crocker
pub_year: 2018
github_username: outsiteco

# add the full url for the github repository
repo: "https://github.com/outsiteco/Canggu"

# urls
# your gh-pages url: https://username.github.io
url: https://outsiteco.github.io
# your repository name: /repository
baseurl: /Canggu

# analytics if desired (and use environment variable on build command)
google_analytics: UA-74844011-1

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
